require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ActivitiesController do

  def mock_activity(stubs={})
    @mock_activity ||= mock_model(Activity, stubs).as_null_object
  end

end
